# Ethereum configuration

ethereum:
  url: http://localhost:8545
  receiptTimeout: 30000ms
  confirmationTimeout: 30000ms
  confirmationBlockCount: 12
  defaultGasLimit: 500000
  minGasPrice: 1000000000
  maxGasPrice: 100000000000
  maxGasLimit: 5000000
  rpcResponseTimeout: 30000ms
  waitReceiptCycleTime: 1000ms
  waitBlockCycleTime: 1000ms
  hubContractAddress: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
  signerPrivateKey: ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
scheduler:
  publishStateTimer: 1000ms





